import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Character, GetCharacterResults } from '../types'


const Home: NextPage<{characters: Character[] }> = ({ characters }) => {

  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {characters.map((item) => {
        return (
          <>
          <p key={item.id}>{item.name}</p>
          <Image src={item.image} alt={item.name} width="200" height="200" />
          </>
        )
      })}


      
    </div>
  )
}



export default Home

export const getServerSideProps: GetServerSideProps = async () => {

  let res = await fetch('https://rickandmortyapi.com/api/character');
    const {results}: GetCharacterResults = await res.json();

  return {
    props: {
      characters: results,
    }
  }
}


// Create something rough that:
// - fetches data
// - uses the Image 
// - Has a form
// - has routing
// - has dynamic routing
// - uses server side props
// - uses static props
